
testcase = ../Sample-Files-Project1
vad:
	@gedit --new-window \
		Makefile \
		Command.java \
		CommandParser.java \
		P1.java \
		coaches_season.txt \
		teams.txt \
		$(testcase)/c.txt \
		$(testcase)/t.txt \
		$(testcase)/sampleIN.in \
		$(testcase)/sample_Input_Output.txt \
		$(testcase)/sampleOUT.out \
		Coach.java \
		Team.java \
		Table.java \
		c.txt \
		t.txt \
		Pair.java \
		README.txt \
		\
		\
		\
		&
		
clean:
	@rm *.class		
